# This configuration file is required for mocks_BPZ. It defines the
# transmission curves, galaxy templates and Bayesian prior required to run the
# BPZ photometric reshift code.

BPZpath = "~/src/bpz-1.99.3"
                        # path of the bpz installation to use
BPZenv = ""             # path to a python2 environment used when calling BPZ
                        # (leave blank to use the default python2 interpreter)
BPZtemp = ""            # temporary directory to use for bpz (I/O intense, e.g.
                        # a ram disk, if blank, defaults to data store)
flux = false            # whether the input columns are fluxes or magnitudes
system = "AB"           # photometric system, must be "AB" or "Vega"
interpolation = 10      # introduces n points of interpolation between the
                        # templates in the color space
odds = 0.68             # redshift confidence limits
templates = "CWWSB4"    # name of the template .list file in the
                        # bpz_path/SED directory

[filters]
# mapping between filter keys (same as used in the column map file for
# mocks_init_pipeline) and paths to transmission curve files compatible with
# BPZ.
i = "~/src/bpz-1.99.3/i_SDSS.res"
                        # transmission files do not need to be in the
                        # bpz_path/FILTER directory

[prior]
name = "hdfn_gen"       # template-magnitude prior module in the bpz_path
                        # directory (filename: prior_[name].py)
filter = "i"            # filter key (one of those listed in the [filters]
                        # section) based on which the prior is evaluated

[sampling]
zmin = 0.01             # minimum redshift probed
zmax = 7.00             # maximum redshift probed
delta_z = 0.01          # redshift resolution, intervals are
                        # logarithmic: (1+z)*dz 
