mask = "samples/GAMA"   # path at which the sample selection bit mask is saved
                        # in the data store

[magnitudes]
mag_r = "..."           # path of r-band magnitude in the data store
