# This configuration file is required for mocks_apertures and mocks_photometry.
# It defines the free parameters of the aperture and photometry methods as well
# as observational PSF sizes and magnitude limits.

legacy = false          # use legacy mode (van den Busch et al. 2020)
limit_sigma = 1.0       # sigma value of the detection (magnitude) limit with
                        # respect to the sky background
no_detect_value = 99.0  # magnitude value assigned to undetected galaxies
SN_detect = 1.0         # signal-to-noise ratio detection limit
SN_floor = 0.2          # numerical lower limit for signal-to-noise ratio

[intrinsic]
r_effective = "shape/R_effective"
                        # path of the effective radius column in the data store
flux_frac = 0.5         # this defines the effective radius by setting the
                        # fraction of the total flux/luminosity for which the
                        # radius of the source is computed

[limits]
# numerical values for the magnitude limits, the keys must be the same as in
# column map file used for mocks_init_pipeline

[PSF]
# numerical values for the PSF FWHM in arcsec, the keys must be the same as in
# column map file used for mocks_init_pipeline

[GAaP]
aper_min = 0.7          # GAaP lower aperture size limit in arcsec
aper_max = 2.0          # GAaP upper aperture size limit in arcsec

[SExtractor]
phot_autoparams = 2.5   # MAG_AUTO-like scaling factor for Petrosian radius,
                        # here applied to intrinsic galaxy size derived from
                        # effective radius
