mask = "samples/SDSS"   # path at which the sample selection bit mask is saved
                        # in the data store

[magnitudes]
mag_g = "..."           # path of g-band magnitude in the data store
mag_r = "..."           # path of r-band magnitude in the data store
mag_i = "..."           # path of i-band magnitude in the data store
# if the following paramters are not set, the QSO selection is not applied
is_central = ""         # path of flag indicating a central host galaxy
lmhalo = ""             # path of logarithmic halo mass
lmstellar = ""          # path of logarithmic stellar mass
