mask = "samples/zCOSMOS"
                        # path at which the sample selection bit mask is saved
                        # in the data store
redshift = "..."        # path of redshift column in the data store

[magnitudes]
mag_Ic = "..."          # path of Johnson Ic-band magnitude in the data store
