#!/usr/bin/env python3
import argparse
import os
import sys

from table_tools import read_footprint_file


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Read the RA/DEC bounds from a footprint file and write '
                    'them to stdout in format: RAmin RAmax DECmin DECmax')
    parser.add_argument(
        '-f', '--footprint-file', required=True,
        help='file in which the survey meta data is collected')
    parser.add_argument(
        '--survey', required=True,
        help='name to idenify survey in ./footprint.txt')
    args = parser.parse_args()

    # read the footprint file
    if not os.path.exists(args.footprint_file):
        sys.exit("ERROR: input file not found: " + args.footprint_file)
    surveys = read_footprint_file(args.footprint_file)
    # get the requested survey and display the bounds
    if args.survey not in surveys:
        sys.exit("ERROR: survey '%s' does not exist" % args.survey)
    else:
        RAmin, RAmax, DECmin, DECmax, area = surveys[args.survey]
        print("%.7f %.7f %.7f %.7f" % (RAmin, RAmax, DECmin, DECmax))
