#!/usr/bin/env python3
import argparse
import os
import sys

from table_tools import read_pointing_file


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Read the RA/DEC bounds of a single pointing from a '
                    'pointing file and write them to stdout in format: '
                    'RAmin RAmax DECmin DECmax')
    parser.add_argument(
        '-p', '--pointings-file', required=True,
        help='file in which the pointings bounds are stored')
    parser.add_argument(
        '-n', type=int, default=1,
        help='n-th pointing to extract, counting from 1 '
             '(default: %(default)s)')
    args = parser.parse_args()

    # read the pointings file
    if not os.path.exists(args.pointings_file):
        sys.exit("ERROR: input file not found: " + args.pointings_file)
    pointings = read_pointing_file(args.pointings_file)
    # get the requested pointing and display the bounds
    if len(pointings) < args.n:
        sys.exit(
            "ERROR: pointing index %d is out of range (1, %d)" % (
                args.n, len(pointings)))
    else:
        name, RAmin, RAmax, DECmin, DECmax = pointings[args.n - 1]
        print("%.7f %.7f %.7f %.7f" % (RAmin, RAmax, DECmin, DECmax))
