# This configuration file is required for mocks_select_sample. It defines the
# the output column name of the selection bit mask and the data columns for the
# selection functions (such as magnitudes or redshift).

bitmask = "samples/DEEP2"  # path at which the sample selection bit mask is saved
                        # in the data store

[selection]
# Mapping form keyword argument names in selection function to column path in
# the data store. Optional arguments can be left blank.
mag_B = "mags/lensed/g"
                        # Johnson B-band magnitude
mag_Rc = "mags/lensed/i"
                        # Johnson Rc-band magnitude
mag_Ic = "mags/lensed/i"
                        # Johnson Ic-band magnitude
