# This configuration file is required for mocks_select_sample. It defines the
# the output column name of the selection bit mask and the data columns for the
# selection functions (such as magnitudes or redshift).

bitmask = "samples/SDSS"   # path at which the sample selection bit mask is saved
                        # in the data store

[selection]
# Mapping form keyword argument names in selection function to column path in
# the data store. Optional arguments can be left blank.
mag_g = "..."           # SDSS g-band magnitude
mag_r = "..."           # SDSS r-band magnitude
mag_i = "..."           # SDSS i-band magnitude
is_central = "..."      # flag indicating if it is central host galaxy
lmhalo = "..."          # logarithmic halo mass
lmstellar = "..."       # logarithmic stellar mass
