mask = "samples/GAMA"   # path at which the sample selection bit mask is saved
                        # in the data store

[selection]
# Mapping form keyword argument names in selection function to column path in
# the data store. Optional arguments can be left blank.
redshift = "..."        # (observed) redshifts
mag_r = "..."           # SDSS r-band magnitude
