#!/usr/bin/env python3
import argparse

from galmock.jobs import flux_to_magnitudes


parser = argparse.ArgumentParser(
    description="Convert fluxes in Flagship to AB magnitudes.")
parser.add_argument(
    "datastore", help="directory in which the data store is located")
parser.add_argument(
    "--flux",
    help="sub-directory within data store which contains the input fluxes")
parser.add_argument(
    "--mag",
    help="sub-directory within data store where the AB magnitudes are stored")
parser.add_argument(
    "--threads", type=int, default=-1,
    help="maximum number of threads to use (default: all)")


def main():
    args = parser.parse_args()
    flux_to_magnitudes(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
