#!/usr/bin/env python3
import argparse
import os
import sys

from mock_processing import PipeLogger, expand_path, open_datastore
from mock_processing.MICE2 import evolution_correction_wrapped
from mock_processing.parallel import ParallelTable
from mock_processing.photometry import load_photometry
from mock_processing.utils import (ModificationStamp, create_column,
                                   row_iter_progress)

parser = argparse.ArgumentParser(
    description='Apply the evolutionary correction to the MICE2 model '
                'magnitudes.')
parser.add_argument(
    "datastore", type=expand_path,
    help="directory in which the data store is located")
parser.add_argument(
    "--mag",
    help="sub-directory within data store which contains the input magnitudes")
parser.add_argument(
    "--evo",
    help="sub-directory within data store where the evolution corrected "
         "magnitudes are stored")
parser.add_argument(
    "--threads", type=int, default=4,
    help="number of threads to use (default: %(default)s)")


def main():

    args = parser.parse_args()
    logger = PipeLogger(__file__, args.datastore)
    timestamp = ModificationStamp(sys.argv)

    # apply the evolution correction to the model magnitudes
    with open_datastore(args.datastore, logger, readonly=False) as table:

        pool = ParallelTable(table, logger)
        pool.set_worker(evolution_correction_wrapped)

        # find redshift column
        z_path = "position/z/true"
        if z_path not in table:
            message = "true redshift column not found: {:}".format(z_path)
            logger.handleException(KeyError(message))
        pool.add_argument_column(z_path)

        # find all magnitude columns
        try:
            model_mags = load_photometry(table, args.mag)
        except KeyError as e:
            logger.handleException(e)

        # create the output columns
        for key, mag_path in model_mags.items():
            # create new output columns
            evo_path = os.path.join(args.evo, key)
            column = create_column(
                table, logger, evo_path, dtype=table[mag_path].dtype.str,
                attr={
                    "description":
                    "{:} with evolution correction applied".format(mag_path)},
                overwrite=True)
            timestamp.register(column)
            # add columns to call signature
            pool.add_argument_column(mag_path)
            pool.add_result_column(evo_path)
        evo_mags = load_photometry(table, args.evo)

        # compute and store the corrected magnitudes in parallel
        pool.execute(args.threads)

        # close the table
        logger.info(
            "computation completed for {:,d} entries".format(len(table)))
        logger.info("updating headers and closing data store")
        timestamp.finalize()


if __name__ == "__main__":
    main()
