#!/usr/bin/env python3
import argparse

from mock_processing.jobs import magnification


parser = argparse.ArgumentParser(
    description="Compute magnitudes corrected for gravitational lensing "
                "magnification in the limit of weak lensing.")
parser.add_argument(
    "datastore", help="directory in which the data store is located")
parser.add_argument(
    "--mag",
    help="sub-directory within data store which contains the input magnitudes")
parser.add_argument(
    "--lensed",
    help="sub-directory within data store where the magnification corrected "
         "magnitudes are stored")
parser.add_argument(
    "--threads", type=int, default=-1,
    help="maximum number of threads to use (default: all)")


def main():
    args = parser.parse_args()
    magnification(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
