#!/usr/bin/env python3
import argparse
import logging

from galmock.jobs import datastore_verify


parser = argparse.ArgumentParser(
    description="Verify the data integrity by using SHA-1 checksums")
parser.add_argument(
    "datastore", help="directory in which the data store is created")


def main():
    logging.basicConfig(
        level=logging.DEBUG, datefmt="%Y-%m-%d %H:%M:%S",
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    args = parser.parse_args()
    datastore_verify(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
