#!/usr/bin/env python3
import argparse
import logging.config

from galmock import GalaxyMock
from galmock.core.utils import expand_path


parser = argparse.ArgumentParser(
    description="Show a table preview of the data store")
parser.add_argument(
    "datastore", type=expand_path,
    help="directory in which the data store is created")


def main():
    args = parser.parse_args()
    with GalaxyMock(args.datastore, True) as mocks:
        print(mocks.datastore)


if __name__ == "__main__":
    main()
