#!/usr/bin/env python
import argparse
import os
import sys

import mock_processing as mocks
from mock_processing.core.bitmask import BitMaskManager
from mock_processing.core.config import DumpSampleConfig, load_sample_config
from mock_processing.matching import DistributionEstimator
from mock_processing import samples


parser = argparse.ArgumentParser(
    description="Apply sample selections on to obtain a mock representation "
                "of a specific photometric or spectroscopic sample.",
    add_help=False)
parser.register("action", "dump", DumpSampleConfig)

parser.add_argument(
    "datastore", help="directory in which the data store is located")
parser.add_argument(
    "--sample", required=True, choices=sorted(samples.REGISTERED_SAMPLES),
    help="name of the sample selection to apply")
parser.add_argument(
    "-c", "--config", required=True,
    help="parameter file in TOML format that defines data columns required "
         "for the sample selection (use --dump to obtain a default parameter "
         "file)")
parser.add_argument(
    "--area", type=float, required=True,
    help="total area in squared degrees on the sky covered by the base "
         "simulation (required by: {:})")
parser.add_argument(
    "--seed", default="sapling",
    help="string to seed the random generator (default: %(default)s, results "
         "are only reproducible for the same number of threads)")
parser.add_argument(
    "--threads", type=int, default=-1,
    help="maximum number of threads to use (default: all)")

help_group = parser.add_argument_group("help and documentation")
help_group.add_argument(
    "-h", "--help", action="help",
    help="show this help message and exit")
help_group.add_argument(
    "--dump", nargs=1, action="dump", metavar="sample",
    choices=sorted(samples.REGISTERED_SAMPLES),
    help="dump a default configuration file to stdout and exit for a given "
         "sample (see --sample for a list of valid names)")


def main():

    args = parser.parse_args()
    logger = mocks.PipeLogger(__file__, args.datastore)

    # check the configuration file
    config = load_sample_config(args.config, logger, sample=args.sample)

    # apply the magnification correction to the model magnitudes
    with mocks.DataStore.open(args.datastore, False, logger=logger) as ds:
        ds.pool.max_threads = args.threads

        logger.info("apply selection funcion: {:}".format(args.sample))

        # allow the worker threads to modify the bitmask column directly
        ds.pool.allow_modify = True

        # make the output column
        BMM = BitMaskManager(args.sample)
        bitmask = ds.add_column(
            config.bitmask, dtype=BMM.dtype, overwrite=True)
        # initialize the selection bit (bit 1) to true, all subsequent
        # selections will be joined with AND
        logger.debug("initializing bit mask")
        bitmask[:] = 1

        # start with photometric selection
        if args.sample in samples.PHOTOMETRIC_SELECTIONS:
            selector_class = samples.PHOTOMETRIC_SELECTIONS[args.sample]
            selector = selector_class(BMM)

            ds.pool.set_worker(selector.apply)
            # select the columns needed for the selection function
            ds.pool.add_argument_column(config.bitmask)
            for name, path in config.selection.items():
                ds.require_column(path)
                ds.pool.add_argument_column(path, keyword=name)

            # apply selection
            ds.pool.execute(seed=args.seed, prefix="photometric selection")

        # optional density sampling
        if args.sample in samples.SAMPLING_SELECTIONS:
            selector_class = samples.SAMPLING_SELECTIONS[args.sample]

            # surface density
            if issubclass(selector_class, samples.DensitySampler):
                selector = selector_class(BMM, args.area, bitmask)
            # redshift weighted density
            else:
                selector = selector_class(
                    BMM, args.area, bitmask, ds[config.selection["redshift"]])

            ds.pool.set_worker(selector.apply)
            # select the columns needed for the selection function
            ds.pool.add_argument_column(config.bitmask)
            # redshift weighted density requires a mock n(z) estimate
            if isinstance(selector, samples.RedshiftSampler):
                ds.pool.add_argument_column(
                    config.selection["redshift"], keyword="redshift")

            # apply selection
            ds.pool.execute(seed=args.seed, prefix="density sampling")

        # add the description attribute to the output column
        bitmask.attr = {"description": BMM.description}

        # show final statistics
        N_mock = samples.DensitySampler.count_selected(bitmask, verbose=False)
        density = "{:.3f} / arcmin²".format(N_mock / args.area / 3600.0)
        logger.info("density of selected objects: " + density)
        logger.info("computation completed for {:,d} entries".format(len(ds)))


if __name__ == "__main__":
    main()
