#!/usr/bin/env python3
import argparse
import logging

from galmock.jobs import datastore_info


parser = argparse.ArgumentParser(
    description="Show information about the data store like the size on disk, "
                "shape, column names, descriptions, attributes and pipeline "
                "logs and processing history.")
parser.add_argument(
    "datastore", help="directory in which the data store is created")
parser.add_argument(
    "-c", "--columns", action="store_true", help="show the column data types")
parser.add_argument(
    "-a", "--attr", action="store_true", help="show the column attributes")
parser.add_argument(
    "-p", "--history", action="store_true", help="show the pipeline history")
parser.add_argument(
    "-l", "--logs", action="store_true",
    help="show the attached pipeline logs")


def main():
    logging.basicConfig(
        level=logging.DEBUG, datefmt="%Y-%m-%d %H:%M:%S",
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    args = parser.parse_args()
    datastore_info(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
