#!/usr/bin/env python3
import argparse
import logging.config

from galmock import GalaxyMock
from galmock.core.config import logging_config
from galmock.core.utils import expand_path


parser = argparse.ArgumentParser(
    description="Delete a set of columns from the data store")
parser.add_argument(
    "datastore", type=expand_path,
    help="directory in which the data store is created")
parser.add_argument(
    "-c", "--columns", nargs="*",
    help="paths of columns in the data store to remove")
parser.add_argument(
    "-v", "--verbose", action="store_true", help="display debugging messages")


def main():
    args = parser.parse_args()
    logging.config.dictConfig(
        logging_config(args.datastore + ".log",
        overwrite=False, verbose=args.verbose))
    with GalaxyMock(args.datastore, False) as mocks:
        mocks.drop_column(args.columns)


if __name__ == "__main__":
    main()
