#!/usr/bin/env python3
import argparse
import logging.config

from galmock.core.config import logging_config
from galmock.core.utils import expand_path
from galmock.jobs import prepare_MICE2


parser = argparse.ArgumentParser(
    description="Apply the evolutionary correction to the MICE2 model "
                "magnitudes.")
parser.add_argument(
    "datastore", type=expand_path,
    help="directory in which the data store is located")
parser.add_argument(
    "--mag",
    help="sub-directory within data store which contains the input magnitudes")
parser.add_argument(
    "--evo",
    help="sub-directory within data store where the evolution corrected "
         "magnitudes are stored")
parser.add_argument(
    "--threads", type=int, default=-1,
    help="maximum number of threads to use (default: all)")
parser.add_argument(
    "-v", "--verbose", action="store_true", help="display debugging messages")


def main():
    args = parser.parse_args()
    logging.config.dictConfig(
        logging_config(args.datastore + ".log",
        overwrite=False, verbose=args.verbose))
    prepare_MICE2(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
