#!/usr/bin/env python3
import argparse
import os
import sys

from mock_processing.jobs import BPZ
from mock_processing.photoz import BpzParser


parser = argparse.ArgumentParser(
    description="Compute magnitudes corrected for gravitational lensing "
                "magnification in the limit of weak lensing.",
    add_help=False)
parser.register("action", "dump", BpzParser.get_dump())

parser.add_argument(
    "datastore", help="directory in which the data store is located")
parser.add_argument(
    "--mag",
    help="sub-directory within data store which contains the input magnitudes")
parser.add_argument(
    "--zphot",
    help="sub-directory within data store where the BPZ output is stored")
parser.add_argument(
    "-c", "--config", required=True,
    help="parameter file in TOML format to configure BPZ")
parser.add_argument(
    "--threads", type=int, default=-1,
    help="maximum number of threads to use (default: all)")

help_group = parser.add_argument_group("help and documentation")
help_group.add_argument(
    "-h", "--help", action="help",
    help="show this help message and exit")
help_group.add_argument(
    "--dump", nargs=0, action="dump",
    help="dump a default BPZ configuration file to stdout and exit")


def main():
    args = parser.parse_args()
    BPZ(**{name: getattr(args, name) for name in vars(args)})


if __name__ == "__main__":
    main()
